### ISSUE TITLE
Javascript : getElementsByClassName

### ISSUE THREAD

**Issue by rodofshadows** [comcaptain/chrome_plugins#1]
I don't know if it is the extension or what but I cannot get this simple test to work.

function getLine() {
    var marr = document.getElementsByClassName('col-xs-12');
    var mel = marr[0];
    console.log(mel);
    console.log(marr)
}
getLine();

I get undefined, no matter how I try to access the indexes of marr. It should be an array and when I send marr to the console, it is populated and I can open it. But I cannot get to it from js in the extension.

I have tried two very different sites to make sure it wasn't the first website.

I can verify a possible bug as when I try the same code in another extension it works fine. I really hope you can fix this, because I wanted to use the css part also which the other extension did not have.

**Comment by comcaptain** [comment]
Can you give me the exact web page url that you applied above scripts?

Since I just tried on this page with below code:

``` javascipt
function getLine() {
var marr = document.getElementsByClassName('js-issue-title');
var mel = marr[0];
console.log(mel);
console.log(marr)
}
getLine();
```

And it works fine.

One possibility: The element with class "col-xs-12" is generated by javascript after `DOMContentLoaded`. While my plugin runs injected javascript before `DOMContentLoaded`, so it'll print undefined for marr.

If this is the case, try below:

``` javascript
document.addEventListener("DOMContentLoaded", function() {
    function getLine() {
        var marr = document.getElementsByClassName('js-issue-title');
        var mel = marr[0];
        console.log(mel);
        console.log(marr)
    }
    getLine();
})
```
